import type { IconType } from "react-icons";
import { PiMicrosoftExcelLogo, PiMicrosoftWordLogo, PiOpenAiLogo } from "react-icons/pi";
import {
    SiApache,
    SiBootstrap,
    SiClaude,
    SiCloudflare,
    SiCss,
    SiDocker,
    SiFigma,
    SiFlutter,
    SiGooglegemini,
    SiHostinger,
    SiHtml5,
    SiJavascript,
    SiLaravel,
    SiMysql,
    SiNetlify,
    SiNextdotjs,
    SiNginx,
    SiOllama,
    SiPhp,
    SiPhpstorm,
    SiPostgresql,
    SiPrisma,
    SiPython,
    SiReact,
    SiSwift,
    SiTailwindcss,
    SiTidb,
    SiTypescript,
    SiVercel,
    SiWebstorm,
    SiWordpress,
} from "react-icons/si";
import { TbDatabase } from "react-icons/tb";
import { VscVscode } from "react-icons/vsc";
import { FacebookIcon } from "./icons/FacebookIcon";
import { GitHubIcon } from "./icons/GithubIcon";
import { LinkedInIcon } from "./icons/LinkedInIcon";
import { RedditIcon } from "./icons/RedditIcon";

export const socialIcon = {
    github: GitHubIcon,
    linkedin: LinkedInIcon,
    facebook: FacebookIcon,
    reddit: RedditIcon,
};

// icons for the skill chips, keyed by the item names in data/portfolio.ts
export const skillIcon: Record<string, IconType> = {
    TypeScript: SiTypescript,
    JavaScript: SiJavascript,
    PHP: SiPhp,
    Python: SiPython,
    Swift: SiSwift,
    React: SiReact,
    "Next.js": SiNextdotjs,
    Laravel: SiLaravel,
    Flutter: SiFlutter,
    Tailwind: SiTailwindcss,
    "Bootstrap 5": SiBootstrap,
    HTML: SiHtml5,
    CSS: SiCss,
    PostgreSQL: SiPostgresql,
    MySQL: SiMysql,
    TiDB: SiTidb,
    "Prisma ORM": SiPrisma,
    "Eloquent ORM": SiLaravel,
    HeidiSQL: TbDatabase,
    Navicat: TbDatabase,
    pgAdmin: TbDatabase,
    Docker: SiDocker,
    Nginx: SiNginx,
    Apache: SiApache,
    Cloudflare: SiCloudflare,
    Vercel: SiVercel,
    Netlify: SiNetlify,
    Hostinger: SiHostinger,
    "VS Code": VscVscode,
    WebStorm: SiWebstorm,
    PhpStorm: SiPhpstorm,
    WordPress: SiWordpress,
    Figma: SiFigma,
    Word: PiMicrosoftWordLogo,
    Excel: PiMicrosoftExcelLogo,
    Claude: SiClaude,
    ChatGPT: PiOpenAiLogo,
    Gemini: SiGooglegemini,
    Ollama: SiOllama,
};
